# Generated by Django 4.2.28 on 2026-08-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('besoin_fonctionnel', models.CharField(choices=[('RF1', 'Réponse FAQ'), ('RF2', 'Recherche de document'), ('RF3', 'Guidage utilisateur'), ('RF4', 'Salutations'), ('RF5', 'Hors périmètre')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentValide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('matiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('etablissement', models.CharField(max_length=150)),
                ('annee', models.PositiveIntegerField()),
                ('lien', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('categorie', models.CharField(blank=True, max_length=50)),
                ('est_guide', models.BooleanField(default=False)),
            ],
        ),
    ]
