# Generated by Django 4.2.30 on 2026-07-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('categorie', models.CharField(blank=True, max_length=50)),
                ('est_guide', models.BooleanField(default=False)),
            ],
        ),
    ]
