# Generated by Django 4.2.30 on 2026-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentValide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('matiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('etablissement', models.CharField(max_length=150)),
                ('annee', models.PositiveIntegerField()),
                ('lien', models.URLField()),
            ],
        ),
    ]
