# Generated by Django 4.2.28 on 2026-08-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributeur', '0024_typedocumentprofessionnel_and_more'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvalide',
            name='ressource',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_valide', to='contributeur.ressources'),
        ),
    ]
