# Generated by Django 4.2.30 on 2026-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_documentvalide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('besoin_fonctionnel', models.CharField(choices=[('RF1', 'Réponse FAQ'), ('RF2', 'Recherche de document'), ('RF3', 'Guidage utilisateur'), ('RF5', 'Hors périmètre')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
