# Generated by Django 4.2.30 on 2026-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='besoin_fonctionnel',
            field=models.CharField(choices=[('RF1', 'Réponse FAQ'), ('RF2', 'Recherche de document'), ('RF3', 'Guidage utilisateur'), ('RF4', 'Salutations'), ('RF5', 'Hors périmètre')], max_length=10),
        ),
    ]
